language: python
python:
  - '3.7'

services:
    - docker

before_install:
  - 'pip install pipenv'
  - 'pipenv sync -d'

    #script:
    #'pipenv run pytest tests'
jobs:
    include:
        - stage: help
        - script:
            - drrobot --help
        - stage: start scans
        - script:
            - drrobot gather -sub github.com
            - ls -la $HOME/.drrobot/output/sublist3r
