dist: bionic
language: python
python:
  - '3.7'

services:
    - docker

install:
    - pip install -r requirements.txt
    - pip install -e .

jobs:
    include:
        - stage: help
          script:
            - drrobot --help
        - stage: start scans
          name: Sublist3r
          script:
            - drrobot gather -sub github.com
            - if [ -z "$(ls -A $HOME/.drrobot/output/github.com/sublist3r)" ]; then exit 1; else echo "Success"; fi;
        - script:
             - drrobot gather -knock github.com
             - if [ -z "$(ls -A $HOME/.drrobot/output/github.com/knock)" ]; then exit 1; else echo "Success"; fi;
          name: Knock
        - script:
             - drrobot gather -amass github.com
             - if [ -z "$(ls -A $HOME/.drrobot/output/github.com/amass)" ]; then exit 1; else echo "Success"; fi;
          name: Amass 
        - script:
             - drrobot gather -turbo github.com
             - if [ -z "$(ls -A $HOME/.drrobot/output/github.com/turbolist3r)" ]; then exit 1; else echo "Success"; fi;
          name: Turbolist3r
        - script:
             - drrobot gather -sfinder github.com
             - if [ -z "$(ls -A $HOME/.drrobot/output/github.com/subfinder)" ]; then exit 1; else echo "Success"; fi;
          name: Subfinder
        - script:
             - drrobot gather -recon github.com
             - if [ -z "$(ls -A $HOME/.drrobot/output/github.com/reconng)" ]; then exit 1; else echo "Success"; fi;
          name: ReconNG
        - script:
             - drrobot gather -altdns github.com
             - if [ -z "$(ls -A $HOME/.drrobot/output/github.com/altdns)" ]; then exit 1; else echo "Success"; fi;
          name: AltDNS
        - script:
             - drrobot gather -anubis github.com
             - if [ -z "$(ls -A $HOME/.drrobot/output/github.com/anubis)" ]; then exit 1; else echo "Success"; fi;
          name: Anubis
        - script:
             - drrobot gather -ctexpo github.com
             - if [ -z "$(ls -A $HOME/.drrobot/output/github.com/ctexpose)" ]; then exit 1; else echo "Success"; fi;
          name: CTExpose
        - script:
             - drrobot gather -ctfr github.com
             - if [ -z "$(ls -A $HOME/.drrobot/output/github.com/ctfr)" ]; then exit 1; else echo "Success"; fi;
          name: CTFR
        - script:
             - drrobot gather -pdlist github.com
             - if [ -z "$(ls -A $HOME/.drrobot/output/github.com/pdlist)" ]; then exit 1; else echo "Success"; fi;
          name: PDList
        - stage: Test screenshots
          name: Webscreenshot
          script:
             - drrobot -h
             - mkdir -p $HOME/.drrobot/output/singlewebsitetest/aggregated
             - echo "https://github.com" > $HOME/.drrobot/output/singlewebsitetest/aggregated/aggregated_protocol_hostnames.txt
             - drrobot inspect --file $HOME/.drrobot/output/singlewebsitetest/aggregated/aggregated_protocol_hostnames.txt  -webscreen singlewebsitetest
             - if [ -z "$(ls -A $HOME/.drrobot/output/singlewebsitetest/webscreenshot)" ]; then exit 1; else echo "Success"; fi;
        - script:
             - drrobot -h
             - mkdir -p $HOME/.drrobot/output/singlewebsitetest/aggregated
             - echo "https://github.com" > $HOME/.drrobot/output/singlewebsitetest/aggregated/aggregated_protocol_hostnames.txt
             - drrobot inspect --file $HOME/.drrobot/output/singlewebsitetest/aggregated/aggregated_protocol_hostnames.txt  -nmapscreen singlewebsitetest
             - if [ -z "$(ls -A $HOME/.drrobot/output/singlewebsitetest/nmapscreen)" ]; then exit 1; else echo "Success"; fi;
          name: NMAP
        - script:
             - drrobot -h
             - mkdir -p $HOME/.drrobot/output/singlewebsitetest/aggregated
             - echo "https://github.com" > $HOME/.drrobot/output/singlewebsitetest/aggregated/aggregated_protocol_hostnames.txt
             - drrobot inspect --file $HOME/.drrobot/output/singlewebsitetest/aggregated/aggregated_protocol_hostnames.txt -eye singlewebsitetest
             - if [ -z "$(ls -A $HOME/.drrobot/output/singlewebsitetest/Eyewitness)" ]; then exit 1; else echo "Success"; fi;
          name: Eyewitness
        - script:
             - drrobot -h
             - mkdir -p $HOME/.drrobot/output/singlewebsitetest/aggregated
             - echo "https://github.com" > $HOME/.drrobot/output/singlewebsitetest/aggregated/aggregated_protocol_hostnames.txt
             - drrobot inspect --file $HOME/.drrobot/output/singlewebsitetest/aggregated/aggregated_protocol_hostnames.txt  -http singlewebsitetest
             - if [ -z "$(ls -A $HOME/.drrobot/output/singlewebsitetest/httpscreenshot)" ]; then exit 1; else echo "Success"; fi;
          name: HTTPScreenshot 
