dist: bionic
language: python
python:
  - '3.7'

services:
    - docker

install:
    - pip install -r requirements.txt
    - pip install -e .

jobs:
    include:
        - stage: help
          script:
            - drrobot --help
        - stage: start scans
          name: Sublist3r
          script:
            - drrobot gather -sub github.com
            - if [ -z "$(ls -la $HOME/.drrobot/output/github.com/sublist3r)" ]; then echo "Success"; else exit 1 done;
        - script:
             - drrobot gather -knock github.com
             - if [ -z "$(ls -la $HOME/.drrobot/output/github.com/knock)" ]; then echo "Success"; else exit 1 done;
          name: Knock
        - script:
             - drrobot gather -amass github.com
             - if [ -z "$(ls -la $HOME/.drrobot/output/github.com/amass)" ]; then echo "Success"; else exit 1 done;
          name: Amass 
        - script:
             - drrobot gather -brute github.com
             - if [ -z "$(ls -la $HOME/.drrobot/output/github.com/brute)" ]; then echo "Success"; else exit 1 done;
          name: Subbrute
        - script:
             - drrobot gather -turbo github.com
             - if [ -z "$(ls -la $HOME/.drrobot/output/github.com/turbolist3r)" ]; then echo "Success"; else exit 1 done;
          name: Turbolist3r
        - script:
             - drrobot gather -sfinder github.com
             - if [ -z "$(ls -la $HOME/.drrobot/output/github.com/subfinder)" ]; then echo "Success"; else exit 1 done;
          name: Subfinder
        - script:
             - drrobot gather -recon github.com
             - if [ -z "$(ls -la $HOME/.drrobot/output/github.com/reconng)" ]; then echo "Success"; else exit 1 done;
          name: ReconNG
        - script:
             - drrobot gather -altdns github.com
             - if [ -z "$(ls -la $HOME/.drrobot/output/github.com/altdns)" ]; then echo "Success"; else exit 1 done;
          name: AltDNS
        - script:
             - drrobot gather -anubis github.com
             - if [ -z "$(ls -la $HOME/.drrobot/output/github.com/anubis)" ]; then echo "Success"; else exit 1 done;
          name: Anubis
        - script:
             - drrobot gather -ctexpo github.com
             - if [ -z "$(ls -la $HOME/.drrobot/output/github.com/ctexpose)" ]; then echo "Success"; else exit 1 done;
          name: CTExpose
        - script:
             - drrobot gather -ctfr github.com
             - if [ -z "$(ls -la $HOME/.drrobot/output/github.com/ctfr)" ]; then echo "Success"; else exit 1 done;
          name: CTFR
        - script:
             - drrobot gather -pdlist github.com
             - if [ -z "$(ls -la $HOME/.drrobot/output/github.com/pdlist)" ]; then echo "Success"; else exit 1 done;
          name: PDList
