dist: bionic
language: python
python:
  - '3.7'

services:
    - docker

install:
    - pip install -r requirements.txt
    - pip install -e .

jobs:
    include:
        - stage: help
        script:
            - drrobot --help
        - stage: start scans
        script:
            - drrobot gather -sub github.com
            - ls -la $HOME/.drrobot/output/sublist3r
